### ISSUE TITLE
ibmcloud上部署的网址能自定义吗？

### ISSUE THREAD

**Issue by ymcoming** [tlmoe/v2fly-cf#6]
现在好像是随机生成的，例如楼下这种：v2ws-comedic-dingo-ka.mybluemix.net

能通过命令在部署时自定义一个网址吗？

**Comment by tlmoe** [comment]
https://github.com/tlmoe/v2fly-cf/blob/master/.github/workflows/deploy-to-ibm.yml#L56

https://docs.run.pivotal.io/devguide/deploy-apps/manifest-attributes.html#routes

**Comment by tvision08** [comment]
大佬能否给个示例？谢谢啦！

**Comment by tlmoe** [comment]
@tvision08 
```
        cat > manifest-ibm.yml << EOF
        ---
        applications:
        - name: v2fly
          memory: 128M
          disk_quota: 128M
          routes:
          - route: v2fly.mybluemix.net
          command: ./v2ray
          buildpacks:
          - binary_buildpack
        EOF
    
    - uses: citizen-of-planet-earth/cf-cli-action@v1
      with:
        cf_api: https://api.us-south.cf.cloud.ibm.com
        cf_username: ${{ secrets.CF_USER_IBM }}
        cf_password: ${{ secrets.CF_PASSWORD_IBM }}
        cf_org: ${{ secrets.CF_ORG_IBM }}
        cf_space: ${{ secrets.CF_SPACE_IBM }}
        command: >
          push v2fly -f manifest-ibm.yml
```
